<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PokerAnalyzer.Data\PokerAnalyzer.Data.csproj" />
    <ProjectReference Include="..\PokerAnalyzer.Common\PokerAnalyzer.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>Nullable</WarningsAsErrors>
  </PropertyGroup>

</Project>
