// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokerAnalyzer.Data.Context;

#nullable disable

namespace PokerAnalyzer.Data.Migrations
{
    [DbContext(typeof(PokerAnalyzerContext))]
    [Migration("20250126200848_Add-Poker-Games")]
    partial class AddPokerGames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("PokerAnalyzer.Data.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Suit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("CardId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Card");
                });

            modelBuilder.Entity("PokerAnalyzer.Data.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PokerGameId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId");

                    b.HasIndex("PokerGameId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("PokerAnalyzer.Data.Models.PokerGame", b =>
                {
                    b.Property<int>("PokerGameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("PokerGameId");

                    b.ToTable("PokerGames");
                });

            modelBuilder.Entity("PokerAnalyzer.Data.Models.PokerGameResults", b =>
                {
                    b.Property<int>("PokerGameResultsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PokerGameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Winner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WinningHand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PokerGameResultsId");

                    b.HasIndex("PokerGameId")
                        .IsUnique();

                    b.ToTable("PokerGameResults");
                });

            modelBuilder.Entity("PokerAnalyzer.Data.Models.Card", b =>
                {
                    b.HasOne("PokerAnalyzer.Data.Models.Player", null)
                        .WithMany("Cards")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokerAnalyzer.Data.Models.Player", b =>
                {
                    b.HasOne("PokerAnalyzer.Data.Models.PokerGame", null)
                        .WithMany("Players")
                        .HasForeignKey("PokerGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokerAnalyzer.Data.Models.PokerGameResults", b =>
                {
                    b.HasOne("PokerAnalyzer.Data.Models.PokerGame", null)
                        .WithOne("Results")
                        .HasForeignKey("PokerAnalyzer.Data.Models.PokerGameResults", "PokerGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokerAnalyzer.Data.Models.Player", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("PokerAnalyzer.Data.Models.PokerGame", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Results")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
