// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokerAnalyzer.Data.Context;

#nullable disable

namespace PokerAnalyzer.Data.Migrations
{
    [DbContext(typeof(PokerAnalyzerContext))]
    [Migration("20250213173727_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("PokerAnalyzer.Data.Models.Player", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("PokerAnalyzer.Data.Models.PokerGame", b =>
                {
                    b.Property<int>("PokerGameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("PokerGameId");

                    b.ToTable("PokerGames");
                });

            modelBuilder.Entity("PokerAnalyzer.Data.Models.PokerGameResults", b =>
                {
                    b.Property<Guid>("Winner")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WinningHand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("PokerGameResults", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PokerAnalyzer.Data.Models.PokerGame", b =>
                {
                    b.OwnsMany("PokerAnalyzer.Data.Models.PokerHand", "PokerHands", b1 =>
                        {
                            b1.Property<int>("PokerHandId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("PokerGameId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PokerHandId");

                            b1.HasIndex("PokerGameId");

                            b1.ToTable("PokerHand");

                            b1.WithOwner()
                                .HasForeignKey("PokerGameId");

                            b1.OwnsMany("PokerAnalyzer.Data.Models.Card", "Cards", b2 =>
                                {
                                    b2.Property<int>("CardId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("PokerHandId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Rank")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Suit")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Value")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("CardId");

                                    b2.HasIndex("PokerHandId");

                                    b2.ToTable("Card");

                                    b2.WithOwner()
                                        .HasForeignKey("PokerHandId");
                                });

                            b1.Navigation("Cards");
                        });

                    b.Navigation("PokerHands");
                });
#pragma warning restore 612, 618
        }
    }
}
